// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczsKQfFEIDKnlzQuYKKXhlZIgvH9H7Vo',
    appId: '1:377840729979:web:11923f1438e7d3733087de',
    messagingSenderId: '377840729979',
    projectId: 'firetwo55-d4f0e',
    authDomain: 'firetwo55-d4f0e.firebaseapp.com',
    storageBucket: 'firetwo55-d4f0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFDF2aqRjOpkjxffFkF9waueqzAuYmlCk',
    appId: '1:377840729979:android:79ac9f64becc4d3a3087de',
    messagingSenderId: '377840729979',
    projectId: 'firetwo55-d4f0e',
    storageBucket: 'firetwo55-d4f0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SQV2CM6qKkyGC1R6gSmG5Vj4DO6SwsI',
    appId: '1:377840729979:ios:d0fdafd857abb8193087de',
    messagingSenderId: '377840729979',
    projectId: 'firetwo55-d4f0e',
    storageBucket: 'firetwo55-d4f0e.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8SQV2CM6qKkyGC1R6gSmG5Vj4DO6SwsI',
    appId: '1:377840729979:ios:d0fdafd857abb8193087de',
    messagingSenderId: '377840729979',
    projectId: 'firetwo55-d4f0e',
    storageBucket: 'firetwo55-d4f0e.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczsKQfFEIDKnlzQuYKKXhlZIgvH9H7Vo',
    appId: '1:377840729979:web:7cd51f232634443e3087de',
    messagingSenderId: '377840729979',
    projectId: 'firetwo55-d4f0e',
    authDomain: 'firetwo55-d4f0e.firebaseapp.com',
    storageBucket: 'firetwo55-d4f0e.appspot.com',
  );
}
